# Generated by Django 3.0.7 on 2020-09-29 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('graph', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetacUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tags', models.TextField(blank=True)),
                ('policy', models.BooleanField(default=False)),
                ('birthday', models.DateField()),
                ('description', models.TextField(max_length=256)),
                ('profileimg', models.ImageField(upload_to='')),
                ('banned', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(default=0)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed', to='Meetac.MeetacUser')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='Meetac.MeetacUser')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(to='Meetac.MeetacUser')),
            ],
        ),
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('choosed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choosed', to='Meetac.MeetacUser')),
                ('chooser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chooser', to='Meetac.MeetacUser')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meetac.MeetacUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='text', max_length=32)),
                ('body', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('recieved', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('id_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='Meetac.MeetacUser')),
                ('id_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Meetac.MeetacUser')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='Meetac.MeetacUser')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='Meetac.MeetacUser')),
            ],
        ),
    ]
