# Generated by Django 3.0.7 on 2020-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
